name: locating_fluttershy
description: "To help us find Fluttershy"

publish_to: 'none'

version: 0.0.7+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  workmanager: ^0.5.2
  package_info_plus: ^7.0.0
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  background_location: ^0.13.0
  geolocator: any
  flutter_background_service: ^5.0.6
  flutter_background_service_android: ^6.2.3
  flutter_background_service_ios: ^5.0.1
  flutter_local_notifications: ^17.2.1
  permission_handler: ^11.3.1
  wakelock_plus: ^1.2.5
  socket_io_client: ^2.0.3+1
  injector: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fluttershy.png
    - assets/double_diagonal_arrow.svg
    - assets/speedometer.svg


flutter_icons:
  image_path: "assets/icon/fluttershy.png"
  android: true
  ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/fluttershy.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/fluttershy.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/fluttershy.png"